In [1]:
import numpy as np

# 加载数据集
dataset = np.load("datasets/Dataset.npy")

# 查看数据集的总数
total_count = len(dataset)
print(f"Total number of records in the dataset: {total_count}")

# 读取前10行数据
print("\nFirst 10 rows of the dataset:")
for i in range(100):
    print(dataset[i])

# 如果数据集中的每一行是一个包含多个元素的数组，则可以使用以下方式打印前10行的每个元素：
# for i in range(10):
#     print(f"Row {i+1}: {dataset[i]}")

Total number of records in the dataset: 4669820

First 10 rows of the dataset:
ur4592644,tt0120884,10,16 January 2005
ur3174947,tt0118688,3,16 January 2005
ur3780035,tt0387887,8,16 January 2005
ur4592628,tt0346491,1,16 January 2005
ur3174947,tt0094721,8,16 January 2005
ur1162550,tt0114891,9,16 January 2005
ur4371033,tt0391198,10,16 January 2005
ur4584306,tt0426568,7,14 January 2005
ur3174947,tt0120601,8,16 January 2005
ur2694867,tt0060196,10,16 January 2005
ur2035667,tt0335245,10,16 January 2005
ur4513109,tt0129161,10,16 January 2005
ur4318504,tt0113724,7,16 January 2005
ur1355507,tt0067023,7,16 January 2005
ur4545306,tt0325596,8,16 January 2005
ur3168872,tt0284867,2,16 January 2005
ur1000879,tt0374900,9,16 January 2005
ur2183556,tt0090062,10,16 January 2005
ur3174947,tt0182789,9,16 January 2005
ur4593110,tt0120370,7,16 January 2005
ur4593029,tt0385004,8,16 January 2005
ur4593101,tt0311289,10,16 January 2005
ur1935667,tt0401233,4,16 January 2005
ur4593048,tt0356618,10,16 January 2005
ur4452141,tt0370263,8,16 January 2005
ur2983202,tt0372588,10,16 January 2005
ur3174947,tt0265086,8,16 January 2005
ur3143319,tt0298814,1,16 January 2005
ur4593124,tt0158539,7,16 January 2005
ur2694867,tt0071385,1,16 January 2005
ur2488512,tt0031725,9,16 January 2005
ur0470968,tt0362270,6,16 January 2005
ur4593070,tt0346491,9,16 January 2005
ur4111911,tt0074486,10,16 January 2005
ur3780035,tt0149937,9,16 January 2005
ur0816433,tt0086203,10,16 January 2005
ur2904081,tt0072826,8,16 January 2005
ur3174947,tt0083658,9,16 January 2005
ur4593205,tt0110442,10,16 January 2005
ur2882544,tt0119365,8,16 January 2005
ur0470968,tt0387564,3,16 January 2005
ur1518804,tt0283426,6,16 January 2005
ur4584029,tt0362270,10,16 January 2005
ur3174947,tt0071230,8,16 January 2005
ur3446219,tt0376541,10,16 January 2005
ur2074560,tt0052846,2,16 January 2005
ur4587088,tt0120804,1,16 January 2005
ur3174947,tt0329334,1,16 January 2005
ur1529007,tt0357277,3,16 January 2005
ur1609501,tt0096933,6,16 January 2005
ur4593421,tt0109370,10,16 January 2005
ur3446219,tt0395169,7,16 January 2005
ur3446219,tt0338751,10,16 January 2005
ur4531500,tt0349683,3,16 January 2005
ur4013711,tt0086960,10,16 January 2005
ur0521881,tt0332452,6,16 January 2005
ur3174947,tt0080455,10,16 January 2005
ur2074560,tt0075261,2,16 January 2005
ur0157498,tt0103874,7,16 January 2005
ur3066329,tt0289879,8,16 January 2005
ur3446219,tt0290002,6,16 January 2005
ur2567136,tt0110776,6,16 January 2005
ur0157498,tt0238546,3,16 January 2005
ur2074560,tt0054333,3,16 January 2005
ur3976881,tt0080365,5,16 January 2005
ur3066329,tt0375173,7,16 January 2005
ur2707735,tt0032285,8,16 January 2005
ur2082018,tt0296658,9,16 January 2005
ur0157498,tt0102034,1,16 January 2005
ur4590696,tt0365677,3,16 January 2005
ur4157001,tt0080934,1,16 January 2005
ur3800949,tt0349903,9,16 January 2005
ur3174947,tt0112573,10,16 January 2005
ur0157498,tt0142804,3,16 January 2005
ur0808507,tt0375063,10,16 January 2005
ur3148015,tt0316732,1,16 January 2005
ur3679103,tt0178868,10,16 January 2005
ur1355507,tt0082533,5,16 January 2005
ur4523728,tt0327056,4,16 January 2005
ur4593736,tt0167456,9,16 January 2005
ur4557989,tt0382357,4,16 January 2005
ur4593726,tt0086081,9,16 January 2005
ur4531500,tt0365748,10,16 January 2005
ur4589592,tt0293508,10,16 January 2005
ur2074560,tt0088100,1,16 January 2005
ur3877341,tt0263488,7,16 January 2005
ur2074560,tt0100665,6,16 January 2005
ur1580268,tt0116275,8,16 January 2005
ur0677266,tt0134847,6,16 January 2005
ur2488512,tt0056876,9,16 January 2005
ur4066513,tt0307453,7,16 January 2005
ur1683802,tt0138094,6,16 January 2005
ur2074560,tt0088772,1,16 January 2005
ur0139258,tt0107247,10,16 January 2005
ur4594181,tt0108174,10,16 January 2005
ur0139258,tt0075261,7,16 January 2005
ur0139258,tt0060672,6,16 January 2005
ur3127857,tt0081470,1,16 January 2005
ur0941716,tt0375210,2,16 January 2005
ur2472494,tt0333766,10,16 January 2005

In [2]:
import numpy as np
import csv

# 加载数据集
dataset = np.load("datasets/Dataset.npy")

# 输出文件名
output_file = "user_rating_temp.csv"

# 打开文件以写入模式创建 csv.writer 对象
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # 写入 header
    writer.writerow(["userID", "tconst", "rating", "reviewDate"])
    
    # 写入数据
    for record in dataset:
        # 将每个记录按照逗号分隔符拆分成字段
        fields = record.split(',')
        # 写入拆分后的字段到 CSV 文件
        writer.writerow(fields)

# 打印提示信息
print(f"Data has been written to {output_file}")

Data has been written to user_rating_temp.csv